FROM node:lts

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies

RUN git clone https://github.com/nordcloud/notejam.git

WORKDIR /usr/src/app/notejam/express/notejam/

RUN npm install

#  Create database schema

WORKDIR  /usr/src/app/notejam/express/notejam/
CMD [ "node", "db.js" ]

EXPOSE 3000

# Launch
CMD [ "node", "./bin/www" ]