FROM node:lts

# Create app directory
WORKDIR /home/runner/work/ncnotejam/ncnotejam

# Install app dependencies

RUN git clone https://github.com/nordcloud/notejam.git

WORKDIR /home/runner/work/ncnotejam/ncnotejam/notejam/express/notejam/

RUN npm install

#  Create database schema

WORKDIR  /home/runner/work/ncnotejam/ncnotejam/notejam/express/notejam/
CMD [ "node", "db.js" ]

EXPOSE 3000

# Launch
CMD [ "node", "./bin/www" ]
